name: Enforce branch naming

on:
    push:
        branches-ignore:
            -master
jobs:
    validate-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Validate branch name requirements
              uses: deepakputhraya/action-branch-name@master
              with:
                regex: '([a-z])+\/([a-z])+'
                min_length: 3
