name: Fail/Success Notification
on:
  workflow_run:
    workflows: [PR Title Checker]
    types: [completed]

jobs:
  on-success:
    name: Success!!!
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}     
        SLACK_MESSAGE: 'PR naming works'
        SLACK_TITLE: Success!!!
  on-failure:
    name: Fail!!!
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'PR naming failed'
        SLACK_TITLE: Failed!!!
        SLACK_COLOR: ${{ #ff0000 }}
